// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course_category.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Blank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{1}
}

func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (m *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(m, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

type CategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryRequest) Reset()         { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()    {}
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{2}
}

func (m *CategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryRequest.Unmarshal(m, b)
}
func (m *CategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryRequest.Marshal(b, m, deterministic)
}
func (m *CategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryRequest.Merge(m, src)
}
func (m *CategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryRequest.Size(m)
}
func (m *CategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryRequest proto.InternalMessageInfo

func (m *CategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategory struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategory) Reset()         { *m = CreateCategory{} }
func (m *CreateCategory) String() string { return proto.CompactTextString(m) }
func (*CreateCategory) ProtoMessage()    {}
func (*CreateCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{3}
}

func (m *CreateCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategory.Unmarshal(m, b)
}
func (m *CreateCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategory.Marshal(b, m, deterministic)
}
func (m *CreateCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategory.Merge(m, src)
}
func (m *CreateCategory) XXX_Size() int {
	return xxx_messageInfo_CreateCategory.Size(m)
}
func (m *CreateCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategory.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategory proto.InternalMessageInfo

func (m *CreateCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CategoryResponse) Reset()         { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()    {}
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{4}
}

func (m *CategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResponse.Unmarshal(m, b)
}
func (m *CategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResponse.Marshal(b, m, deterministic)
}
func (m *CategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResponse.Merge(m, src)
}
func (m *CategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryResponse.Size(m)
}
func (m *CategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResponse proto.InternalMessageInfo

func (m *CategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type CategoryListCategories struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryListCategories) Reset()         { *m = CategoryListCategories{} }
func (m *CategoryListCategories) String() string { return proto.CompactTextString(m) }
func (*CategoryListCategories) ProtoMessage()    {}
func (*CategoryListCategories) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{5}
}

func (m *CategoryListCategories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryListCategories.Unmarshal(m, b)
}
func (m *CategoryListCategories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryListCategories.Marshal(b, m, deterministic)
}
func (m *CategoryListCategories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryListCategories.Merge(m, src)
}
func (m *CategoryListCategories) XXX_Size() int {
	return xxx_messageInfo_CategoryListCategories.Size(m)
}
func (m *CategoryListCategories) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryListCategories.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryListCategories proto.InternalMessageInfo

func (m *CategoryListCategories) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*Category)(nil), "pb.Category")
	proto.RegisterType((*Blank)(nil), "pb.blank")
	proto.RegisterType((*CategoryRequest)(nil), "pb.CategoryRequest")
	proto.RegisterType((*CreateCategory)(nil), "pb.CreateCategory")
	proto.RegisterType((*CategoryResponse)(nil), "pb.CategoryResponse")
	proto.RegisterType((*CategoryListCategories)(nil), "pb.CategoryListCategories")
}

func init() {
	proto.RegisterFile("proto/course_category.proto", fileDescriptor_fde79cb73866aac8)
}

var fileDescriptor_fde79cb73866aac8 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x9b, 0x94, 0x9f, 0xf6, 0x0a, 0x01, 0x19, 0x84, 0xa2, 0xb0, 0x44, 0x9e, 0x3a, 0xa0,
	0x54, 0x2a, 0x13, 0x12, 0x2c, 0x54, 0x2a, 0x0b, 0x03, 0x2a, 0x1b, 0x0b, 0x8a, 0x9d, 0x13, 0xb2,
	0x28, 0xb6, 0xb1, 0x5d, 0x24, 0x9e, 0x81, 0x97, 0x46, 0xb8, 0x8d, 0x9b, 0x10, 0xb1, 0xb0, 0x5d,
	0xbe, 0xbb, 0xfb, 0x74, 0x77, 0x31, 0x9c, 0x6b, 0xa3, 0x9c, 0x9a, 0x70, 0xb5, 0x32, 0x16, 0x9f,
	0x79, 0xe9, 0xf0, 0x45, 0x99, 0xcf, 0xc2, 0x53, 0x12, 0x6b, 0x46, 0x1f, 0x60, 0x30, 0xdb, 0x50,
	0x92, 0x40, 0x2c, 0xaa, 0x34, 0xca, 0xa3, 0xf1, 0x70, 0x11, 0x8b, 0x8a, 0x10, 0xd8, 0x91, 0xe5,
	0x1b, 0xa6, 0xb1, 0x27, 0x3e, 0x26, 0x39, 0x8c, 0x2a, 0xb4, 0xdc, 0x08, 0xed, 0x84, 0x92, 0x69,
	0xdf, 0xa7, 0x9a, 0x88, 0xee, 0xc3, 0x2e, 0x5b, 0x96, 0xf2, 0x95, 0xde, 0xc1, 0x51, 0xad, 0x5e,
	0xe0, 0xfb, 0x0a, 0xad, 0x0b, 0xc6, 0xe8, 0x6f, 0x63, 0xdc, 0x35, 0xce, 0x21, 0x99, 0x19, 0x2c,
	0x1d, 0x86, 0x49, 0xff, 0xe7, 0xb9, 0x86, 0xe3, 0xed, 0x40, 0x56, 0x2b, 0x69, 0x91, 0x8c, 0x61,
	0x50, 0x5f, 0xc5, 0xdb, 0x46, 0xd3, 0x83, 0x42, 0xb3, 0x22, 0xd4, 0x85, 0x2c, 0x9d, 0xc3, 0x59,
	0x4d, 0xef, 0x85, 0x75, 0x9b, 0x58, 0xa0, 0x25, 0x17, 0x00, 0x3c, 0x7c, 0xa5, 0x51, 0xde, 0xef,
	0x58, 0x1a, 0xf9, 0xe9, 0x57, 0xb4, 0xbd, 0xcb, 0x23, 0x9a, 0x0f, 0xc1, 0x91, 0xdc, 0x74, 0x36,
	0x3c, 0x69, 0xf5, 0xaf, 0xcf, 0x97, 0x9d, 0xb6, 0xe1, 0x7a, 0x05, 0xda, 0x23, 0x57, 0x90, 0xfc,
	0x1a, 0x69, 0xf8, 0x53, 0xe9, 0x7f, 0x43, 0x96, 0x35, 0x9b, 0xda, 0x65, 0xb4, 0x77, 0x7b, 0xf8,
	0x34, 0x12, 0xd2, 0xa1, 0x91, 0xe5, 0x72, 0xa2, 0x19, 0xdb, 0xf3, 0x2f, 0xe3, 0xf2, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x54, 0xf3, 0x37, 0x8c, 0x38, 0x02, 0x00, 0x00,
}
